# Generated by Django 3.2.5 on 2021-08-18 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_auto_20210814_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(default=None, max_length=50)),
                ('asset_desc', models.CharField(default=None, max_length=50)),
                ('asset_sn', models.CharField(default=None, max_length=50)),
                ('asset_pn', models.CharField(default=None, max_length=50)),
                ('asset_cal_due', models.CharField(max_length=250, null=True)),
                ('asset_cal_last', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16, unique=True)),
                ('employee_first_name', models.CharField(max_length=30, unique=True)),
                ('employee_last_name', models.CharField(max_length=30, unique=True)),
                ('emp_image', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(default=None, max_length=50)),
                ('loc_desc', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.department')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=25, unique=True)),
                ('res_image', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignedTo',
        ),
        migrations.RemoveField(
            model_name='task',
            name='details',
        ),
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.RemoveField(
            model_name='task',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='job_type',
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='link_doc',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='poc_email',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='prod_desc',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='prod_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='support_type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='task_desc',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='part_num',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='serial_num',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_order',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.status'),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.status'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.employee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.department'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.resource'),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.status'),
        ),
        migrations.AddField(
            model_name='asset',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.department'),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.location'),
        ),
        migrations.AddField(
            model_name='task',
            name='test_environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.testenvironment'),
        ),
        migrations.AddField(
            model_name='task',
            name='test_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.testtype'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.department'),
        ),
        migrations.AlterField(
            model_name='task',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.resource'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.status'),
        ),
    ]
