# Generated by Django 3.2.5 on 2021-08-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20210818_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(default=None, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='resource',
            name='res_image',
            field=models.ImageField(default=None, null=True, upload_to=None),
        ),
    ]
