# Generated by Django 3.2.5 on 2021-09-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='test_environment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
